name: k6 Load Test
run-name: ${{ github.actor }} k6 Load Test
on: [push]
jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: grafana/k6-action@v0.2.0
      with:
        filename: src/tests/LoadTest.ts
        flags: --out json=results.json

      - name: Upload performance test results
      - uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: results.json
    - run: npm install -g bats
    - run: bats -v
