 name: Main workflow
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
 on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:  ["main", "feature/**"]
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Pushed'
        # Input has to be provided for the workflow to run
        required: true
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'Manual run'
        # Input has to be provided for the workflow to run
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run local k6 test
      - uses: grafana/k6-action@v0.2.0
        with:
          filename: src/simpleTest.js
      # Runs a single command using the runners shell
      - name: Send greeting
      - run: echo "Hello ${{ github.event.inputs.name }}"
