name: k6 SMOKE Test
run-name: ${{ github.actor }} k6 Load Test
on: [push]
jobs:
 check-bats-version:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v1
    - uses: grafana/k6-action@v0.2.0
      with:
        filename: src/SmokeTest.js
        
    - run: npm install -g bats
    - run: bats -v
